name: Build VS Code Extension

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 使用 Node 20 LTS
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Install vsce
        run: npm install -g vsce@2.17.0

      - name: Package extension
        run: vsce package

      - name: Upload VSIX
        uses: actions/upload-artifact@v4
        with:
          name: vscode-extension
          path: "*.vsix"
